# app.R
# shinyplanr deployment for {country}
# Generated by shinyplanr::create_shinyplanr_template()
#
# DO NOT edit this file directly.
# To update the app configuration, re-run:
#   setup/setup-app.R

# Load region configuration (generated by setup-app.R)
shinyplanr::load_config("config/shinyplanr_config.rds")

# Launch the app
shinyplanr::run_app()
