# deploy.R
# Deploy {country} shinyplanr app to Posit Connect
# Generated by shinyplanr::create_shinyplanr_template()
#
# FIRST TIME SETUP:
#   1. Create an API key at: https://connect.posit.cloud/connect/#!/api-keys
#   2. Run:
#      rsconnect::setAccountInfo(name='<name>', token='<token>', secret='<secret>')
#
# BEFORE DEPLOYING: ensure config is up to date
#   source('setup/setup-app.R')
#
# IF USING renv: update the lock file before deploying
#   renv::snapshot()
#
# TO UPGRADE shinyplanr:
#   renv::update('shinyplanr')
#   source('setup/setup-app.R')
#   renv::snapshot()
#   source('deploy.R')

files_to_deploy <- c(
  "app.R",
  "deploy.R",
  list.files("config", full.names = TRUE, recursive = TRUE),
  list.files("www",    full.names = TRUE, recursive = TRUE)
)

# Include renv files needed by Posit Connect.
# Connect reads renv.lock and installs packages server-side — do NOT include
# renv/library/ (local compiled binaries that won't run on Connect's Linux server).
if (file.exists("renv.lock"))        files_to_deploy <- c(files_to_deploy, "renv.lock")
if (file.exists(".Rprofile"))        files_to_deploy <- c(files_to_deploy, ".Rprofile")
if (file.exists("renv/activate.R")) files_to_deploy <- c(files_to_deploy, "renv/activate.R")

rsconnect::deployApp(
  appName     = "{country}",
  appFiles    = files_to_deploy,
  forceUpdate = TRUE
)
