# deploy.R
# Deploy {country} shinyplanr app to Posit Connect
# Generated by shinyplanr::create_shinyplanr_template()
#
# =============================================================================
# FIRST TIME SETUP
# =============================================================================
#   1. Create an API key at: https://connect.posit.cloud/connect/#!/api-keys
#   2. Run:
#      rsconnect::setAccountInfo(name='<name>', token='<token>', secret='<secret>')
#
# =============================================================================
# NORMAL DEPLOYMENT (no shinyplanr upgrade)
# =============================================================================
#   1. Re-run setup/3_setup_app.R  (regenerates config/shinyplanr_config.rds)
#   2. source('deploy.R')
#
# =============================================================================
# UPGRADING shinyplanr
# =============================================================================
#
# Step 1 -- Refresh safe-to-overwrite template files (app.R, deploy.R,
#           1_setup_enviro.R, new content/*.md files that don't yet exist):
#
#   shinyplanr::update_shinyplanr_template()
#
# Step 2 -- Reinstall packages at new versions and lock renv.lock:
#
#   source('setup/1_setup_enviro.R')   # re-installs at HEAD + your extras
#                                      # renv::snapshot() is called at the end
#
# Step 3 -- Check if 3_setup_app.R needs manual updates:
#
#   shinyplanr::schema_changelog()     # prints what changed between versions
#   # Update setup/3_setup_app.R manually if needed.
#   # DO NOT overwrite it -- it contains your customisations.
#
# Step 4 -- Regenerate the config and redeploy:
#
#   source('setup/3_setup_app.R')
#   source('deploy.R')
#
# =============================================================================

files_to_deploy <- c(
  "app.R",
  "deploy.R",
  list.files("config", full.names = TRUE, recursive = TRUE),
  list.files("www",    full.names = TRUE, recursive = TRUE)
)

# Include renv files needed by Posit Connect.
# Connect reads renv.lock and installs packages server-side — do NOT include
# renv/library/ (local compiled binaries that won't run on Connect's Linux server).
if (file.exists("renv.lock"))        files_to_deploy <- c(files_to_deploy, "renv.lock")
if (file.exists(".Rprofile"))        files_to_deploy <- c(files_to_deploy, ".Rprofile")
if (file.exists("renv/activate.R")) files_to_deploy <- c(files_to_deploy, "renv/activate.R")

rsconnect::deployApp(
  appName     = "{country}",
  appFiles    = files_to_deploy,
  forceUpdate = TRUE
)
