#' Load region configuration for shinyplanr
#'
#' Reads a region-specific configuration file generated by \code{setup-app.R}
#' and makes all configuration objects (spatial data, options, text content,
#' themes) available to the shinyplanr app modules.
#'
#' This function \strong{must} be called before \code{\link{run_app}()}. The
#' \code{app.R} file generated by \code{\link{create_shinyplanr_template}()}
#' calls this automatically.
#'
#' @param config_path Character. Path to the \code{shinyplanr_config.rds} file.
#'   Defaults to \code{"config/shinyplanr_config.rds"}, which is the location
#'   used by projects created with \code{create_shinyplanr_template()}.
#'   The path is resolved relative to the current working directory.
#'
#' @return Invisibly returns the config list. Called for its side effect of
#'   populating the shinyplanr package namespace with the region configuration.
#'
#' @export
#'
#' @examples
#' \dontrun{
#' # In a deployment project's app.R:
#' shinyplanr::load_config("config/shinyplanr_config.rds")
#' shinyplanr::run_app()
#' }
load_config <- function(config_path = "config/shinyplanr_config.rds") {

  if (!file.exists(config_path)) {
    stop(
      "Config file not found: ",
      normalizePath(config_path, mustWork = FALSE), "\n\n",
      "Have you run setup-app.R to generate it?\n",
      "Expected: config/shinyplanr_config.rds\n",
      "To generate: source('data-raw/<YourRegion>/setup-app.R')"
    )
  }

  config <- readRDS(config_path)

  # Validate schema version and required keys — stops with clear error if wrong
  .validate_config(config, config_path)

  # Normalise the agr (attribute-geometry-relationship) factor on every sf
  # object in the config.  When an sf is saved to RDS in one R session and
  # loaded in another, the agr factor's internal integer codes can become
  # inconsistent with its levels.  sf's dplyr method uses agr to reconstruct
  # the sf after select(); a stale agr causes geometry to be silently dropped
  # instead of kept stickily, which crashes fCheckFeatureNo, splnr_plot, and
  # any other code that calls dplyr::select() on the loaded sf objects.
  # st_set_agr(x, "constant") rebuilds the factor cleanly; "constant" is the
  # correct value for all planning-unit attributes (feature presence/absence,
  # cost values, etc. are constant per geometry).
  config <- lapply(config, function(x) {
    if (inherits(x, "sf")) sf::st_set_agr(x, "constant") else x
  })

  # Store all config objects in the dedicated shinyplanr_config environment.
  # This environment's *binding* in the namespace is locked (you cannot
  # replace the env object itself), but the environment it points to is NOT
  # locked — keys can be freely added or overwritten without unlockBinding().
  # This avoids the R CMD check NOTE for "possibly unsafe calls".
  for (nm in names(config)) {
    shinyplanr_config[[nm]] <- config[[nm]]
  }

  message(
    "shinyplanr config loaded: ",
    config$options$app_title %||% "(no title)",
    " (schema v", config$schema_version, ")"
  )

  invisible(config)
}
